AgendApp/Models/ContactoModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AgendApp.Models
{
    public class ContactoModel
    {
        public int IdContacto { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }

    }
}

AgendApp/Models/ErrorViewModel.cs
using System;

namespace AgendApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AgendApp/Controllers/ContactosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using AgendApp.Models;
using AgendApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace AgendApp.Controllers
{
    public class ContactosController : Controller
    {
        IContactos contactoService;
        public ContactosController(IConfiguration configuration)
        {
            contactoService = new ContactoService(configuration["ConnectionStrings:DefaultConnection"]);
        }
        public IActionResult Index()
        {
            return View();
        }
        public JsonResult GetContactos()
        {
            return Json(contactoService.GetContactos());
        }
        public JsonResult AddContacto(ContactoModel contacto)
        {
            try
            {
                contactoService.AddContacto(contacto);
                return Json("ok");
            }
            catch (Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(ex.Message);
            }
        }
    }
}

AgendApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AgendApp.Models;

namespace AgendApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AgendApp/Views/Contactos/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Lista de contactos</h1>

<p class="text-danger">@ViewBag.ErrorMessage</p>


<div class="card mb-3">
    <div class="card-header">
        Agregar nuevo contacto
    </div>
    <div class="card-body">
        <form id="frmSubmit">
            <div class="form-group">
                <input type="text" value="" placeholder="Nombre" class="form-control" id="txtNombre" />
            </div>
            <div class="form-group">
                <input type="text" value="" placeholder="Telefono" class="form-control" id="txtTelefono" />
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" id="btnSave" />
            </div>
        </form>
    </div>
</div>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Telefono</th>
        </tr>
    </thead>
    <tbody id="output"></tbody>
</table>
@section Scripts{
    <script>
        $.ajax({
            method: "GET",
            url: "Contactos/GetContactos",
            success: function (response) {
                $.each(response, function (index, contacto) {
                    $("#output").append("<tr><td>" + contacto.nombre + "</td><td>" + contacto.telefono + "</td></tr>");
                })
            }
        })
        $(document).ready(function () {
            $("#btnSave").click(function (e) {
                e.preventDefault();
                $.ajax({
                    method: "POST",
                    url: "Contactos/AddContacto",
                    data: {
                        Nombre: $("#txtNombre").val(),
                        Telefono: $("#txtTelefono").val(),
                    },
                    success: function (data) {
                        console.log(data);
                        ShowSnackbar(snacktype.SUCCESS, snackposition.TOPRIGHT, data);
                        $("#frmSubmit").submit();
                    },
                    error: function (xhr, status, error) {
                        console.log(xhr);
                        ShowSnackbar(snacktype.ERROR, snackposition.TOPRIGHT, xhr.responseJSON);
                    }
                })
            })
        })
    </script>
}

AgendApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<button onclick="ShowSnackbar(snacktype.DEFAULT, snackposition.TOPRIGHT)">Snack test</button>

AgendApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AgendApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/snackbar.css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AgendApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contactos" asp-action="Index">Contactos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AgendApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <div id="snackbar">
        Se agrego correctamente
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/snackbar.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

AgendApp/Views/Shared/_Mensajes.cshtml
<p>@ViewBag.ErrorMessage</p>